function DCM = PQW2ECI(i,RAAN, w)

DCM = [cos(RAAN)*cos(w)-sin(RAAN)*cos(i)*sin(w), -cos(RAAN)*sin(w)-sin(RAAN)*cos(i)*cos(w), sin(RAAN)*sin(i);...
    sin(RAAN)*cos(w)+cos(RAAN)*cos(i)*sin(w), -sin(RAAN)*sin(w)+cos(RAAN)*cos(i)*cos(w), -cos(RAAN)*sin(i);...
    sin(i)*sin(w), sin(i)*cos(w), cos(i)];